# Generated by Django 4.1.2 on 2022-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workingteam",
            name="team",
        ),
        migrations.AddField(
            model_name="workingteam",
            name="group",
            field=models.CharField(
                choices=[
                    ("SALES", "SALES"),
                    ("SUPPORT", "SUPPORT"),
                    ("MANAGEMENT", "MANAGEMENT"),
                ],
                default="MANAGEMENT",
                max_length=20,
            ),
        ),
    ]
